# This file should contain your API keys for production deployment
# DO NOT commit this file to Git - it's in .gitignore

# Copy your API keys here when deploying
# DATALASTIC_API_KEY = "your_datalastic_key_here"
# TWELVEDATA_API_KEY = "your_12data_key_here"
# MOCK_MODE = "false"

# For local development, you can use .env file instead